log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /root/config
    watch: true

entryPoints:
  websecure:
    address: ":443"
  web:
    address: ":8080"

certificatesresolvers:
  letsencrypt:
    acme:
      storage: /root/letsencrypt/acme.json
      tlsChallenge: { }

